<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My To-Do App</title>
    <script src="/js/display.js" defer></script>
</head>
<body>
    <div class="todoList">
        <h1 class="listTitle">THINGS I NEED TO DO</h1>
        <div class="listEntries"> <?= \Todo\Classes\ViewHelpers\DisplayTodosViewHelper::displayTodos($data); ?> </div>
    </div>
    <div class="addToList">
        <input type="text" id="addTodo" placeholder="I need to..." />
        <input type="submit" id="submitTodo" value="Add To List" />
    </div>
</body>
</html>