<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>To Do App</title>
    <script src="/js/display.js" defer></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/styles.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 todoList">
                <h1 class="col-xs-12 listTitle">THINGS I NEED TO DO</h1>
                <?= \Todo\Classes\ViewHelpers\DisplayTodosViewHelper::displayTodos($data); ?>
            </div>
            <div class="editList">
                <span id="displayInput">&#x2723;</span>
            </div>
        </div>
        <div class="row">
            <div class="addToList">
                <input type="text" id="addTodo" class="addTodoInput" placeholder="I need to..." />
                <input type="submit" id="submitTodo" class="submitTodoBtn" value="Add To List" />
            </div>
        </div>
    </div>
</body>
</html>